server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/microservices-security-realm
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/products/**
                - Method=GET,POST
            - id: inventory-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/inventory/**
                - Method=GET
            - id: order-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/orders/**
                - Method=POST
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.route.RouteDefinitionLocator: DEBUG