version: '4'
services:
  inventorydb:
    image: mysql:8.3.0
    container_name: inventorydb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
        - ./data:/var/lib/mysql
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql